# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: react-auto-scaling-demo:1.0
        imagePullPolicy: IfNotPresent  # Cambiado de Never a IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1m"  # Más bajo para forzar escalado rápido
            memory: "16Mi"
          limits:
            cpu: "10m"
            memory: "32Mi"