# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: react-auto-scaling-demo:1.0
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
        resources:
          requests:  # Límites mínimos
            cpu: "1m"  #  0.1% de CPU - Más bajo para forzar escalado rápido
            memory: "16Mi"
          limits:    # Límites máximos
            cpu: "10m"    # 1% de CPU
            memory: "32Mi"